/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.logging.Level;
import java.util.logging.Logger;
//import view.SanPham;

/**
 *
 * @author KHAI
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    TrangChu a = new TrangChu();
    LoaiSP b = new LoaiSP();
    SanPham c = new SanPham();
    NhaCungCap1 d = new NhaCungCap1();
    Kho e = new Kho();
    NhanVienView f = new NhanVienView();
    KhachHangView g = new KhachHangView();
    HoaDonView h = new HoaDonView();
    public Home() {
        initComponents();
        main.add(a);
        main.add(b);
        main.add(c);
        main.add(d);
        main.add(e);
        main.add(f);
        main.add(g);
        main.add(h);
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
        h.setVisible(false);
    }
    //width : 210
    //height : 600
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pMmenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_frmSP = new javax.swing.JButton();
        btn_frmLoaiSP = new javax.swing.JButton();
        btn_frmNCC = new javax.swing.JButton();
        btn_frmNhanVien = new javax.swing.JButton();
        btn_frmTrangChu = new javax.swing.JButton();
        btn_frmKhachHang = new javax.swing.JButton();
        btn_frmHoaDon = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        main = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1320, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1410, 800));

        pMmenu.setBackground(new java.awt.Color(102, 255, 255));
        pMmenu.setPreferredSize(new java.awt.Dimension(210, 800));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-fast-food-64.png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(0, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Fast food");

        btn_frmSP.setBackground(new java.awt.Color(51, 255, 255));
        btn_frmSP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_frmSP.setText("Sản phẩm");
        btn_frmSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_frmSPMouseClicked(evt);
            }
        });
        btn_frmSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_frmSPActionPerformed(evt);
            }
        });

        btn_frmLoaiSP.setBackground(new java.awt.Color(51, 255, 255));
        btn_frmLoaiSP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_frmLoaiSP.setText("Loại sản phẩm");
        btn_frmLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_frmLoaiSPActionPerformed(evt);
            }
        });

        btn_frmNCC.setBackground(new java.awt.Color(51, 255, 255));
        btn_frmNCC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_frmNCC.setText("Nhà cung cấp");
        btn_frmNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_frmNCCActionPerformed(evt);
            }
        });

        btn_frmNhanVien.setBackground(new java.awt.Color(102, 255, 255));
        btn_frmNhanVien.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_frmNhanVien.setText("Nhân viên");
        btn_frmNhanVien.setActionCommand("");
        btn_frmNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_frmNhanVienActionPerformed(evt);
            }
        });

        btn_frmTrangChu.setBackground(new java.awt.Color(51, 255, 255));
        btn_frmTrangChu.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_frmTrangChu.setText("Trang chủ");
        btn_frmTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_frmTrangChuActionPerformed(evt);
            }
        });

        btn_frmKhachHang.setBackground(new java.awt.Color(102, 255, 255));
        btn_frmKhachHang.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_frmKhachHang.setText("Khách hàng");
        btn_frmKhachHang.setActionCommand("");
        btn_frmKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_frmKhachHangActionPerformed(evt);
            }
        });

        btn_frmHoaDon.setBackground(new java.awt.Color(102, 255, 255));
        btn_frmHoaDon.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_frmHoaDon.setText("Hóa đơn ");
        btn_frmHoaDon.setActionCommand("");
        btn_frmHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_frmHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMmenuLayout = new javax.swing.GroupLayout(pMmenu);
        pMmenu.setLayout(pMmenuLayout);
        pMmenuLayout.setHorizontalGroup(
            pMmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_frmLoaiSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_frmSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_frmNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_frmNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pMmenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(btn_frmTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_frmKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_frmHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pMmenuLayout.setVerticalGroup(
            pMmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMmenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_frmTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_frmLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_frmSP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_frmNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_frmKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_frmNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_frmHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jPanel4.setLayout(new java.awt.CardLayout());

        main.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pMmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 842, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(main)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_frmLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_frmLoaiSPActionPerformed
        // TODO add your handling code here:
        a.setVisible(false);
        b.setVisible(true);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
        h.setVisible(false);
    }//GEN-LAST:event_btn_frmLoaiSPActionPerformed

    private void btn_frmSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_frmSPActionPerformed
        // TODO add your handling code here:
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(true);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
        h.setVisible(false);
    }//GEN-LAST:event_btn_frmSPActionPerformed

    private void btn_frmSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_frmSPMouseClicked
        // TODO add your handling code here:
        //a.setVisible(true);
    }//GEN-LAST:event_btn_frmSPMouseClicked

    private void btn_frmNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_frmNCCActionPerformed
        // TODO add your handling code here:
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(true);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
        h.setVisible(false);
    }//GEN-LAST:event_btn_frmNCCActionPerformed

    private void btn_frmTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_frmTrangChuActionPerformed
        // TODO add your handling code here:
        a.setVisible(true);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
        h.setVisible(false);
    }//GEN-LAST:event_btn_frmTrangChuActionPerformed

    private void btn_frmNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_frmNhanVienActionPerformed
        // TODO add your handling code here:
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(true);
        g.setVisible(false);
        h.setVisible(false);
    }//GEN-LAST:event_btn_frmNhanVienActionPerformed

    private void btn_frmKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_frmKhachHangActionPerformed
        // TODO add your handling code here:
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(true);
        h.setVisible(false);
    }//GEN-LAST:event_btn_frmKhachHangActionPerformed

    private void btn_frmHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_frmHoaDonActionPerformed
        // TODO add your handling code here:
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
        h.setVisible(true);
    }//GEN-LAST:event_btn_frmHoaDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_frmHoaDon;
    private javax.swing.JButton btn_frmKhachHang;
    private javax.swing.JButton btn_frmLoaiSP;
    private javax.swing.JButton btn_frmNCC;
    private javax.swing.JButton btn_frmNhanVien;
    private javax.swing.JButton btn_frmSP;
    private javax.swing.JButton btn_frmTrangChu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLayeredPane main;
    private javax.swing.JPanel pMmenu;
    // End of variables declaration//GEN-END:variables
}
