/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import DAO.dsLoaiSPClass;
import Models.LoaiSPClass;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author KHAI
 */
public class LoaiSP extends javax.swing.JPanel {

    /**
     * Creates new form LoaiSP
     */
    dsLoaiSPClass dslsp;
    ArrayList<LoaiSPClass> ds_List;
    int vitri = 0;
    int flag = 0;

    public LoaiSP() {
        initComponents();
        dslsp = new dsLoaiSPClass();
        ds_List = dslsp.LaydsLoaiSP();
        AnHienButton(true);
        AnHienTextBox(true);
        HienthiTable();   
    }
    private void HienthiTable() {
    if (ds_List != null && tbl_LoaiSP13 != null) {
        String[] Hearder = {"Mã loại", "Tên loại"};
        DefaultTableModel model = new DefaultTableModel(Hearder, 0);
        
        for (LoaiSPClass c : ds_List) {
            Object[] o = {c.MaLoaiSP, c.LoaiSP};
            model.addRow(o);
        }
        
        tbl_LoaiSP13.setModel(model);
        
        if (vitri >= 0 && vitri < model.getRowCount()) {
            tbl_LoaiSP13.setRowSelectionInterval(vitri, vitri);
        } else {
            tbl_LoaiSP13.clearSelection(); // Clear selection if vitri is out of range
        }
    } else {
        System.out.println("Error: ds_List or tbl_LoaiSP is null.");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel16 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        tbl_LoaiSP13 = new javax.swing.JTable();
        txt_tim = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_MaLoai = new javax.swing.JTextField();
        txt_tenLoai = new javax.swing.JTextField();
        btn_tim = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_Luu = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 800));

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)), "Danh sách loại sản phẩm"));
        jPanel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        tbl_LoaiSP13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_LoaiSP13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "MALOAISP", "LOAISP"
            }
        ));
        tbl_LoaiSP13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_LoaiSP13MouseClicked(evt);
            }
        });
        jScrollPane14.setViewportView(tbl_LoaiSP13);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(307, 307, 307))
        );

        txt_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)), "Thông tin loại sản phẩm"));
        jPanel1.setForeground(new java.awt.Color(51, 0, 51));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Mã loại");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Tên loại");

        txt_MaLoai.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        txt_tenLoai.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaLoai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenLoai))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_tim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_tim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loupe_428094.png"))); // NOI18N
        btn_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOẠI SẢN PHẨM");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)), "Tác vụ"));
        jPanel2.setForeground(new java.awt.Color(51, 0, 51));

        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa ");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_Luu.setText("Lưu");
        btn_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(137, 137, 137)
                            .addComponent(txt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_tim, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(txt_tim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
    }// </editor-fold>//GEN-END:initComponents
     private void HienThiTextBox(int vitri) {
        LoaiSPClass c = ds_List.get(vitri);
        txt_MaLoai.setText(c.MaLoaiSP);
        txt_tenLoai.setText(c.LoaiSP);
    }
    private LoaiSPClass Chuyendoitextbox_sangdoituong()
    {
       LoaiSPClass c = new LoaiSPClass(txt_MaLoai.getText(), txt_tenLoai.getText(), 0);
       return c;
    }
    private boolean kiemTraNhapDayDu() {
    String maLoaiSP = txt_MaLoai.getText().trim();
    String tenLoaiSP = txt_tenLoai.getText().trim();

    if (maLoaiSP.isEmpty() || tenLoaiSP.isEmpty()) {
        JOptionPane.showMessageDialog(btn_Luu, "Vui lòng nhập đầy đủ thông tin cho Mã Loại SP và Tên Loại SP", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    return true;
    }
     private void XoaTextBox()
    {
        txt_MaLoai.setText("");
        txt_tenLoai.setText("");
    }
    private void AnHienTextBox(boolean t)
    {
        txt_MaLoai.setEnabled(!t);
        //txt_tenLoai.setEnabled(t);
    }
    private void AnHienButton(boolean t)
    {
        btn_Them.setEnabled(t);
        btn_sua.setEnabled(t);
        btn_Xoa.setEnabled(t);
        btn_Luu.setEnabled(!t);
    }
    String previousAction = "";
    
    private void tbl_LoaiSP13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_LoaiSP13MouseClicked
        // TODO add your handling code here:
        vitri = tbl_LoaiSP13.getSelectedRow();
        HienThiTextBox(vitri);
    }//GEN-LAST:event_tbl_LoaiSP13MouseClicked

    private void txt_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timActionPerformed

    private void btn_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timActionPerformed
        // TODO add your handling code here:
        if(txt_tim.getText() != null)
        ds_List = dslsp.TimKiemLoaiSP(txt_tim.getText());
        vitri = 0;
        HienthiTable();
        HienThiTextBox(vitri);
    }//GEN-LAST:event_btn_timActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        flag = 1;
        txt_MaLoai.setText(dslsp.PhatSinhMa());
        //txt_MaLoai.setText("");
        txt_tenLoai.setText("");
        AnHienTextBox(true);
        AnHienButton(false);
        previousAction = "Them";
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        LoaiSPClass c = Chuyendoitextbox_sangdoituong();
        flag = 3;
        txt_MaLoai.setText("");
        txt_tenLoai.setText("");
        AnHienButton(false);
        previousAction = "Xoa";
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        flag = 2;
        txt_MaLoai.setText("");
        txt_tenLoai.setText("");
        AnHienTextBox(true);
        AnHienButton(false);
        previousAction = "Sua";
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuActionPerformed
        // TODO add your handling code here:
        if (kiemTraNhapDayDu())
        {
            String message = "Bạn có chắc chắn muốn ";
            if (previousAction.equals("Them")) {
                message += "thêm không?";
            }
            if (previousAction.equals("Xoa")) {
                message += "xóa không?";
            }
            if (previousAction.equals("Sua")) {
                message += "sửa không?";
            }

            int confirm = JOptionPane.showConfirmDialog(btn_Luu, message, "Xác nhận", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION)
            {
                LoaiSPClass c = Chuyendoitextbox_sangdoituong();
                if( flag == 1 )
                {

                    dslsp.ThemLoaiSP(c);
                    flag= 0; //Để bấm các tính năng khác
                    XoaTextBox();
                    AnHienButton(true); //2. Nút lưu khóa, các nút khác hiện.
                    AnHienTextBox(false); //Khóa textbox lại cho người dùng không sửa bậy
                    //lbThongBao.setText("Hãy chọn 1 thao tác");
                    JOptionPane.showMessageDialog(btn_Luu, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE); //cái này thêm ko dc nó vẫn chạy !!!
                }

                if (flag == 2 )
                {
                    dslsp.SuaLoaiSP(c);
                    flag= 0;
                    XoaTextBox();
                    AnHienButton(true); //2. Nút lưu khóa, các nút khác hiện.
                    AnHienTextBox(false); //Khóa textbox lại cho người dùng không sửa bậy
                    //lbThongBao.setText("Hãy chọn 1 thao tác");
                    JOptionPane.showMessageDialog(btn_Luu, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }

                if (flag == 3)
                {
                    dslsp.XoaLoaiSP(c);
                    XoaTextBox();
                    //Khi xóa xong, 1. Nút lưu vẫn mở, các nút khác vẫn khóa (cho ng dùng xóa tiếp đôi tg khác. (cho đến khi ấn hủy). 2.
                        //anHienText(true); //khi xóa xong thì vẫn còn hiện
                        JOptionPane.showMessageDialog(btn_Luu, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }

                //flag= 0;
                //xoaTextBox();
                dslsp = new dsLoaiSPClass();
                ds_List = dslsp.LaydsLoaiSP();
                HienthiTable();
                    //anHienText(true);
                }
            }
    }//GEN-LAST:event_btn_LuuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Luu;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_tim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JTable tbl_LoaiSP13;
    private javax.swing.JTextField txt_MaLoai;
    private javax.swing.JTextField txt_tenLoai;
    private javax.swing.JTextField txt_tim;
    // End of variables declaration//GEN-END:variables

    void setLoaiSP(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
