/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import DAO.daoNhaCungCap;
import Models.NhaCungCapClass;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author KHAI
 */
public class NhaCungCap1 extends javax.swing.JPanel {

    /**
     * Creates new form NhaCungCap1
     */
    daoNhaCungCap dsncc;
    ArrayList<NhaCungCapClass> ds_List;
    int vitri = 0;
    int flag = 0;
    public NhaCungCap1() {
        initComponents();
        dsncc = new daoNhaCungCap();
        ds_List = dsncc.LaydsNhaCungCap();
        HienthiTable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Xoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_Them = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_MaNCC = new javax.swing.JTextField();
        txt_tenNCC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_DiaChi = new javax.swing.JTextField();
        btn_Luu = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        txt_tim = new javax.swing.JTextField();
        btn_Tim = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_NCC = new javax.swing.JTable();

        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NHÀ CUNG CẤP");

        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)), "Thông tin nhà cung cấp"));
        jPanel1.setForeground(new java.awt.Color(51, 0, 51));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Mã nhà cung cấp");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Tên nhà cung cấp");

        txt_MaNCC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        txt_tenNCC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Số Điện Thoại");
        jLabel5.setToolTipText("");

        txt_SDT.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Đia Chỉ");
        jLabel6.setToolTipText("");

        txt_DiaChi.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_MaNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(txt_tenNCC))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaNCC)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_SDT))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenNCC)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_DiaChi))
                .addGap(39, 39, 39))
        );

        btn_Luu.setText("Lưu");
        btn_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa ");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_Tim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loupe_428094.png"))); // NOI18N
        btn_Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)), "Danh sách nhà cung cấp"));

        tbl_NCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MaNCC", "TenNCC", "SDT ", "DiaChi"
            }
        ));
        tbl_NCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NCCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_NCC);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 953, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(txt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(btn_Them)
                        .addGap(36, 36, 36)
                        .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_tim)
                    .addComponent(btn_Tim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
     private void HienthiTable() {
    if (ds_List != null && tbl_NCC != null) {
        String[] Hearder = {"MaNCC", "TenNCC", "SDT", "DiaChi"};
        DefaultTableModel model = new DefaultTableModel(Hearder, 0);
        
        for (NhaCungCapClass c : ds_List) {
            Object[] o = {c.MaNCC, c.TenNCC, c.SDT, c.DiaChi};
            model.addRow(o);
        }
        
        tbl_NCC.setModel(model);
        
        if (vitri >= 0 && vitri < model.getRowCount()) {
            tbl_NCC.setRowSelectionInterval(vitri, vitri);
        } else {
            tbl_NCC.clearSelection(); // Clear selection if vitri is out of range
        }
    } else {
        System.out.println("Error: ds_List or tbl_NCC is null.");
    }
    }
      private void HienThiTextBox(int vitri) {
        NhaCungCapClass c = ds_List.get(vitri);
        txt_MaNCC.setText(c.MaNCC);
        txt_tenNCC.setText(c.TenNCC);
        txt_SDT.setText(c.SDT);
        txt_DiaChi.setText(c.DiaChi);
    }
      private NhaCungCapClass Chuyendoitextbox_sangdoituong()
    {
       NhaCungCapClass c = new NhaCungCapClass(txt_MaNCC.getText(), txt_tenNCC.getText(),txt_SDT.getText(), txt_DiaChi.getText(), 0);
       return c;
    }
    private void AnHienTextBox(boolean t)
    {
        txt_MaNCC.setEnabled(!t);
        //txt_tenLoai.setEnabled(t);
    }
    private void AnHienButton(boolean t)
    {
        btn_Them.setEnabled(t);
        btn_sua.setEnabled(t);
        btn_Xoa.setEnabled(t);
        btn_Luu.setEnabled(!t);
    }
     private void XoaTextBox()
    {
        txt_MaNCC.setText("");
        txt_tenNCC.setText("");
        txt_DiaChi.setText("");
        txt_SDT.setText("");
    }
    public boolean isValidPhoneNumber() {
        String phoneNumber = txt_SDT.getText();
        // Định dạng số điện thoại: 10 chữ số và bắt đầu từ số 0
        String regex = "^0[0-9]{9}$";
        
        // Biên dịch regex
        Pattern pattern = Pattern.compile(regex);
        
        // So khớp regex với chuỗi số điện thoại
        Matcher matcher = pattern.matcher(phoneNumber);
        
        // Trả về kết quả so khớp
        return matcher.matches();
    }
     private boolean kiemTraNhapDayDu() {
    String MaNCC = txt_MaNCC.getText().trim();
    String TenNCC = txt_tenNCC.getText().trim();
    String DiaChi = txt_DiaChi.getText().trim();
    String Sdt = txt_SDT.getText().trim();

    if (MaNCC.isEmpty() || TenNCC.isEmpty() || DiaChi.isEmpty() || Sdt.isEmpty()) {
        JOptionPane.showMessageDialog(btn_Luu, "Vui lòng nhập đầy đủ thông tin", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    return true;
    }
    String previousAction = "";
    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        NhaCungCapClass c = Chuyendoitextbox_sangdoituong();
        flag = 3;
        txt_MaNCC.setText("");
        txt_tenNCC.setText("");
        AnHienButton(false);
        previousAction = "Xoa";
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        flag = 1;
        txt_MaNCC.setText(dsncc.PhatSinhMa());
        txt_tenNCC.setText("");
        txt_DiaChi.setText("");
        txt_SDT.setText("");
        AnHienTextBox(true);
        AnHienButton(false);
        previousAction = "Them";
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuActionPerformed
        // TODO add your handling code here:
        if (kiemTraNhapDayDu())
        {
            if (kiemTraNhapDayDu()) {
                // Chỉ kiểm tra định dạng số điện thoại khi thêm hoặc sửa
                if ((flag == 1) && !isValidPhoneNumber()) {
                    JOptionPane.showMessageDialog(btn_Luu, "Bạn nhập sai định dạng Số điện thoại", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            String message = "Bạn có chắc chắn muốn ";
            if (previousAction.equals("Them")) {
                message += "thêm không?";
            }
            if (previousAction.equals("Xoa")) {
                message += "xóa không?";
            }
            if (previousAction.equals("Sua")) {
                message += "sửa không?";
            }

            int confirm = JOptionPane.showConfirmDialog(btn_Luu, message, "Xác nhận", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION)
            {
                NhaCungCapClass c = Chuyendoitextbox_sangdoituong();
                if( flag == 1 )
                {

                    dsncc.ThemNhaCungCap(c);
                    flag= 0; //Để bấm các tính năng khác
                    XoaTextBox();
                    AnHienButton(true); //2. Nút lưu khóa, các nút khác hiện.
                    AnHienTextBox(false); //Khóa textbox lại cho người dùng không sửa
                    //lbThongBao.setText("Hãy chọn 1 thao tác");
                    JOptionPane.showMessageDialog(btn_Luu, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE); //cái này thêm ko dc nó vẫn chạy !!!
                }

                if (flag == 2)
                {
                    dsncc.SuaNhaCungCap(c);
                    flag= 0;
                    XoaTextBox();
                    AnHienButton(true); //2. Nút lưu khóa, các nút khác hiện.
                    AnHienTextBox(false); //Khóa textbox lại cho người dùng không sửa 
                    //lbThongBao.setText("Hãy chọn 1 thao tác");
                    JOptionPane.showMessageDialog(btn_Luu, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }

                if (flag == 3)
                {
                    dsncc.XoaNhaCungCap(c);
                    XoaTextBox();
                    //Khi xóa xong, 1. Nút lưu vẫn mở, các nút khác vẫn khóa (cho ng dùng xóa tiếp đôi tg khác. (cho đến khi ấn hủy). 2.
                        //anHienText(true); //khi xóa xong thì vẫn còn hiện
                        JOptionPane.showMessageDialog(btn_Luu, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    }

                    //flag= 0;
                    //xoaTextBox();
                    dsncc = new daoNhaCungCap();
                    ds_List = dsncc.LaydsNhaCungCap();
                    HienthiTable();
                    //anHienText(true);
                }
            }
        }
    }//GEN-LAST:event_btn_LuuActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        flag = 2;
        txt_MaNCC.setText("");
        txt_tenNCC.setText("");
        AnHienTextBox(true);
        AnHienButton(false);
        previousAction = "Sua";
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimActionPerformed
        // TODO add your handling code here:
        if(txt_tim.getText() != null)
        ds_List = dsncc.TimKiemNhaCungCap(txt_tim.getText());
        vitri = 0;
        HienthiTable();
        HienThiTextBox(vitri);
    }//GEN-LAST:event_btn_TimActionPerformed

    private void tbl_NCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_NCCMouseClicked
        // TODO add your handling code here:
        vitri = tbl_NCC.getSelectedRow();
        HienThiTextBox(vitri);
    }//GEN-LAST:event_tbl_NCCMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Luu;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Tim;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_sua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_NCC;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_MaNCC;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_tenNCC;
    private javax.swing.JTextField txt_tim;
    // End of variables declaration//GEN-END:variables
}
