/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.daoSanPham;
import Models.SanPhamClass;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.rmi.CORBA.Util;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KHAI
 */
public class SanPham extends javax.swing.JPanel {

    /**
     * Creates new form SanPham
     */
    daoSanPham dssp;
    ArrayList<SanPhamClass> ds_List;
    int vitri = 0;
    int flag = 0;
    String Hinh="";
    private DefaultComboBoxModel cbomodel;
    public SanPham() {
        initComponents();
        dssp = new daoSanPham();
        ds_List = dssp.LaydsSanPham();
        HienthiTable();
//        HienThiComBoBox();
    }
//    void HienThiComBoBox(){
//        String sql = "SELECT LOAISP FROM LOAISANPHAM where TRANGTHAI = 0";
//        
//        try {
//            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=DA_QL_CHTAN", "sa", "khai754123");
//            PreparedStatement statement = conn.prepareStatement(sql);
//            ResultSet result = statement.executeQuery();
//            
//            // Xóa tất cả các mục trước khi thêm dữ liệu mới
//            if (cbomodel == null) {
//            cbomodel = new DefaultComboBoxModel();
//            cbo_LoaiSP.setModel(cbomodel);
//            }
//        
//        // Xóa tất cả các mục trước khi thêm dữ liệu mới
//            cbomodel.removeAllElements();
//        
//            while(result.next()) { // Nếu có kết quả trả về từ truy vấn
//                String loaiSP = result.getString("LOAISP");
//                cbomodel.addElement(loaiSP); // Thêm từng loại sản phẩm vào mô hình
//            }
//            
//        conn.close(); // Đóng kết nối sau khi sử dụng // Đóng kết nối sau khi sử dụng
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, "Lỗi khi truy vấn cơ sở dữ liệu: " + ex.getMessage());
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Luu = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_Tim = new javax.swing.JButton();
        txt_tim = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_tenSP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_MaSP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_GiaNhap = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_GiaSP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lbl_Hinh = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_MaLoai = new javax.swing.JTextField();
        btn_Xoa = new javax.swing.JButton();
        btn_Them = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_SanPham = new javax.swing.JTable();

        btn_Luu.setText("Lưu");
        btn_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa ");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_Tim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loupe_428094.png"))); // NOI18N
        btn_Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SẢN PHẨM");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)), "Thông tin sản phẩm"));
        jPanel1.setForeground(new java.awt.Color(51, 0, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Mã loại sản phẩm");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Tên sản phẩm");

        txt_tenSP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Mã sản phẩm");
        jLabel5.setToolTipText("");

        txt_MaSP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Giá nhập");
        jLabel6.setToolTipText("");

        txt_GiaNhap.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Giá sản phẩm");

        txt_GiaSP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Hình ảnh");
        jLabel9.setToolTipText("");

        lbl_Hinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_Hinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_HinhMouseClicked(evt);
            }
        });

        jButton1.setText("x 2");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("x 3");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txt_MaLoai.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_tenSP)
                            .addComponent(txt_MaLoai, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_GiaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addComponent(txt_GiaNhap)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Hinh, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_MaSP)
                    .addComponent(txt_MaLoai))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tenSP)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_GiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_GiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lbl_Hinh, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)), "Danh sách sản phẩm"));

        tbl_SanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MaSP", "MaLoaiSP", "TenSP", "GiaNhap", "GiaSP", "Hình ảnh", "TrangThai"
            }
        ));
        tbl_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_SanPham);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(txt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Them)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void HienthiTable() {
        if (ds_List != null && tbl_SanPham != null) {
            String[] Hearder = {"MaSP", "MALOAISP", "TenSP", "GiaNhap", "GiaSP", "HinhAnh"};
            DefaultTableModel model = new DefaultTableModel(Hearder, 0);

            for (SanPhamClass c : ds_List) {
                Object[] o = {c.MaSP, c.MaLoaiSP, c.TenSP, c.GiaNhap, c.GiaSP, c.HinhAnh};
                model.addRow(o);
            }

            tbl_SanPham.setModel(model);

            if (vitri >= 0 && vitri < model.getRowCount()) {
                tbl_SanPham.setRowSelectionInterval(vitri, vitri);
            } else {
                tbl_SanPham.clearSelection(); // Clear selection if vitri is out of range
            }
        } else {
            System.out.println("Error: ds_List or tbl_SanPham is null.");
        }
    }

    
    String previousAction = "";
    
    private boolean kiemTraNhapDayDu() {
    String MaLoaiSP = txt_MaLoai.getText().trim();
    String MaSP = txt_MaSP.getText().trim();
    String TenSP = txt_tenSP.getText().trim();
    String GiaNhap = txt_GiaNhap.getText().trim();
    String GiaSP = txt_GiaSP.getText().trim();
    //String HinhAnh = lbl_Hinh.getText().trim();

    if (MaLoaiSP.isEmpty() || MaSP.isEmpty() || TenSP.isEmpty() || TenSP.isEmpty() || GiaNhap.isEmpty() || GiaSP.isEmpty()){
        JOptionPane.showMessageDialog(btn_Luu, "Vui lòng nhập đầy đủ thông tin", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    return true;
    }
    public int isGiaNhapNhoHonGiaSP() {
        try {
            int giaNhap = Integer.parseInt(txt_GiaNhap.getText());
            int giaSP = Integer.parseInt(txt_GiaSP.getText());

            // Kiểm tra nếu giá nhập nhỏ hơn hoặc bằng 0
            if (giaNhap <= 0) {
                return -1; // Giá nhập nhỏ hơn hoặc bằng 0
            }

            // So sánh giá nhập và giá sản phẩm
            if (giaNhap < giaSP) {
                return 1; // Giá nhập nhỏ hơn giá sản phẩm
            } else {
                return 0; // Giá nhập không nhỏ hơn giá sản phẩm
            }
        } catch (NumberFormatException e) {
            return -2; // Giá trị nhập vào không hợp lệ
        }
    }


    private void HienThiTextBox(int vitri) {
        SanPhamClass c = ds_List.get(vitri);
        txt_MaSP.setText(c.MaSP);
        txt_MaLoai.setText(c.MaLoaiSP);
//        cbo_LoaiSP.setSelectedItem(c.MaLoaiSP);
        txt_tenSP.setText(c.TenSP);
        txt_GiaNhap.setText(String.valueOf(c.GiaNhap));
        txt_GiaSP.setText(String.valueOf(c.GiaSP));
        Uploadhinh(c.HinhAnh);
    }
    private SanPhamClass Chuyendoitextbox_sangdoituong() {
     SanPhamClass c = new SanPhamClass(txt_MaSP.getText(),txt_MaLoai.getText(), txt_tenSP.getText(), Integer.parseInt(txt_GiaNhap.getText()), Integer.parseInt(txt_GiaSP.getText()), lbl_Hinh.getText(), 0);
       return c;
}

     private void AnHienTextBox(boolean t)
    {
        txt_MaSP.setEnabled(!t);
    }
    private void AnHienButton(boolean t)
    {
        btn_Them.setEnabled(t);
        btn_sua.setEnabled(t);
        btn_Xoa.setEnabled(t);
        btn_Luu.setEnabled(!t);
    }
     private void XoaTextBox()
    {
        txt_MaSP.setText("");
        txt_MaLoai.setText("");
        txt_tenSP.setText("");
        txt_GiaNhap.setText("");
        txt_GiaSP.setText("");
        lbl_Hinh.setText("");
    }
    private String ChonHinh() {
       JFileChooser open = new JFileChooser();
       File defaultDirectory = new File("src\\images\\");
       open.setCurrentDirectory(defaultDirectory);
       int kq = open.showOpenDialog(null);
       String hinh = "";
       if(kq == open.APPROVE_OPTION) {
           File f = open.getSelectedFile();
           String filename = f.getAbsolutePath();
           String []chuoi = filename.split("\\\\");
           hinh = chuoi[chuoi.length-2] + "\\" + chuoi[chuoi.length-1];
           
           //hinh=f.getName();
       }
        return hinh;
    }   
    private void Uploadhinh(String hinh) {
    // Đảm bảo đường dẫn tới thư mục chứa hình ảnh là chính xác
    String path = "src\\images\\" + hinh;
    
    // Kiểm tra file hình ảnh có tồn tại không
    File file = new File(path);
    if (!file.exists()) {
        System.out.println("File không tồn tại: " + path);
        return;
    }
    
    // Tải và đặt hình ảnh vào label
    ImageIcon image1 = new ImageIcon(path);
    Image im = image1.getImage();
    ImageIcon icon = new ImageIcon(im.getScaledInstance(lbl_Hinh.getWidth(), 
            lbl_Hinh.getHeight(), Image.SCALE_SMOOTH));
    lbl_Hinh.setIcon(icon);
}
    private void btn_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuActionPerformed
        // TODO add your handling code here:
        if (kiemTraNhapDayDu()) {
            int checkResult = isGiaNhapNhoHonGiaSP();
            if (checkResult == -1) {
                JOptionPane.showMessageDialog(btn_Luu, "Giá nhập phải lớn hơn 0.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (checkResult == 0) {
                JOptionPane.showMessageDialog(btn_Luu, "Giá nhập phải nhỏ hơn giá bán.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (checkResult == -2) {
                JOptionPane.showMessageDialog(btn_Luu, "Giá trị nhập vào không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String message = "Bạn có chắc chắn muốn ";
            if (previousAction.equals("Them")) {
                message += "thêm không?";
            }
            if (previousAction.equals("Xoa")) {
                message += "xóa không?";
            }
            if (previousAction.equals("Sua")) {
                message += "sửa không?";
            }

            int confirm = JOptionPane.showConfirmDialog(btn_Luu, message, "Xác nhận", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION)
            {
                SanPhamClass c = Chuyendoitextbox_sangdoituong();
                if( flag == 1 )
                {
                    dssp.ThemSanPham(c);
                    flag = 0; //Để bấm các tính năng khác
                    XoaTextBox();
                    AnHienButton(true); //2. Nút lưu khóa, các nút khác hiện.
                    AnHienTextBox(false); //Khóa textbox lại cho người dùng không sửa bậy
                    //lbThongBao.setText("Hãy chọn 1 thao tác");
                    JOptionPane.showMessageDialog(btn_Luu, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }

                if (flag == 2 )
                {
                    dssp.SuaSanPham(c);
                    flag= 0;
                    XoaTextBox();
                    AnHienButton(true); //2. Nút lưu khóa, các nút khác hiện.
                    AnHienTextBox(false); //Khóa textbox lại cho người dùng không sửa bậy
                    //lbThongBao.setText("Hãy chọn 1 thao tác");
                    JOptionPane.showMessageDialog(btn_Luu, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

                }

                if (flag == 3)
                {
                    dssp.XoaSanPham(c);
                    XoaTextBox();
                        JOptionPane.showMessageDialog(btn_Luu, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
                dssp = new daoSanPham();
                ds_List = dssp.LaydsSanPham();
                HienthiTable();
            }
        }
    }//GEN-LAST:event_btn_LuuActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        flag = 2;
        AnHienTextBox(true);
        AnHienButton(false);
        previousAction = "Sua";
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimActionPerformed
        // TODO add your handling code here:
        if(txt_tim.getText() != null)
        ds_List = dssp.TimKiemSanPham(txt_tim.getText());
        vitri = 0;
        HienthiTable();
        HienThiTextBox(vitri);
    }//GEN-LAST:event_btn_TimActionPerformed

    private void tbl_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SanPhamMouseClicked
        // TODO add your handling code here:
        vitri = tbl_SanPham.getSelectedRow();
        HienThiTextBox(vitri);

    }//GEN-LAST:event_tbl_SanPhamMouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        flag = 1;
        txt_MaSP.setText(dssp.PhatSinhMa());
        AnHienTextBox(true);
        AnHienButton(false);
        previousAction = "Them";
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        SanPhamClass c = Chuyendoitextbox_sangdoituong();
        flag = 3;
        AnHienTextBox(true);
        AnHienButton(false);
        previousAction = "Xoa";
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void lbl_HinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HinhMouseClicked
        // TODO add your handling code here:
        String duongdan = ChonHinh();
        lbl_Hinh.setText(duongdan);
        Uploadhinh(duongdan);
    }//GEN-LAST:event_lbl_HinhMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String giaNhapStr = txt_GiaNhap.getText().trim();
    
    // Kiểm tra xem giá nhập có giá trị hợp lệ không
    if (!giaNhapStr.isEmpty()) {
        try {
            // Chuyển đổi giá nhập thành số
            int giaNhap = Integer.parseInt(giaNhapStr);
            
            // Tính toán giá bán mới bằng cách nhân giá nhập với 1.5
            int giaBan = giaNhap * 2;
            
            // Cập nhật giá bán mới lên text field của giá bán
            txt_GiaSP.setText(String.valueOf(giaBan));
        } catch (NumberFormatException e) {
            // Xử lý nếu giá trị nhập không phải là số
            JOptionPane.showMessageDialog(this, "Giá nhập không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        } else {
            // Xử lý nếu giá nhập không được nhập vào
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá nhập", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String giaNhapStr = txt_GiaNhap.getText().trim();
         giaNhapStr = giaNhapStr.replace(".", "");
        
    
    // Kiểm tra xem giá nhập có giá trị hợp lệ không
        if (!giaNhapStr.isEmpty()) {
            try {
                // Chuyển đổi giá nhập thành số
                int giaNhap = Integer.parseInt(giaNhapStr);
            
            // Tính toán giá bán mới bằng cách nhân giá nhập với 1.5
                int giaBan = giaNhap * 3;
            

                // Cập nhật giá bán mới lên text field của giá bán
                txt_GiaSP.setText(String.valueOf(giaBan));
            } catch (NumberFormatException e) {
                // Xử lý nếu giá trị nhập không phải là số
                JOptionPane.showMessageDialog(this, "Giá nhập không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            } else {
                // Xử lý nếu giá nhập không được nhập vào
                JOptionPane.showMessageDialog(this, "Vui lòng nhập giá nhập", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Luu;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Tim;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Hinh;
    private javax.swing.JTable tbl_SanPham;
    private javax.swing.JTextField txt_GiaNhap;
    private javax.swing.JTextField txt_GiaSP;
    private javax.swing.JTextField txt_MaLoai;
    private javax.swing.JTextField txt_MaSP;
    private javax.swing.JTextField txt_tenSP;
    private javax.swing.JTextField txt_tim;
    // End of variables declaration//GEN-END:variables

}
